import { Metadata } from "next";
import { Inter, Montserrat } from "next/font/google";

import Header from "../components/header";
import Footer from "../components/footer";
import { ToastProvider } from "../components/ToastProvider" // Adjust the path to your ToastProvider file
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
const montserrat = Montserrat({ weight: "200", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <ToastProvider>
          <Header />
          <main>{children}</main>
          <Footer />
        </ToastProvider>
      </body>
    </html>
  );
}
